Pandas Library:
Used for data processing and analysis.

In [1]:
import pandas as pd

Creating a Pandas Dataframe

since i dont have any datasets with me, i will be using my college attendance report in xls file as a dataset

In [3]:
attendance_df= pd.read_excel('/attendance.xlsx')
type(attendance_df)

pandas.core.frame.DataFrame

In [5]:
attendance_df.head()

,"ODISHA UNIVERSITY OF TECHNOLOGY AND RESEARCH, BHUBANESWAR",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Student Attendance Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Semester:2nd ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Class Started :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Attendance report till :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,% Attendance,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print(attendance_df)

   ODISHA UNIVERSITY OF TECHNOLOGY AND RESEARCH, BHUBANESWAR Unnamed: 1  \
0                           Student Attendance Report               NaN
1   Semester:2nd                                  ...               NaN
2                                                 NaN               NaN
3                                                 NaN               NaN
4                                                 NaN               NaN
5                                        Subject Name               NaN
6                                        Subject Code               NaN
7                                                 NaN               NaN
8                                                 Sno           Roll No
9                                                   1          24140003
10                                                  2          24140004
11                                                  3          24140005
12                                                  4          24140006
13                                                  5          24140007
14                                                  6          24140008
15                                                  7          24140009
16                                                  8          24140010
17                                                  9          24140011
18                                                 10          24140012
19                                                 11          24140013
20                                                 12          24140014
21                                                 13          24140015
22                                                 14          24140016
23                                                 15          24140017
24                                                 16          24140018
25                                                 17          24140019
26                                                 18          24140020
27                          Name of Subject Teacher:                NaN
28                                                NaN               NaN

                    Unnamed: 2            Unnamed: 3  \
0                          NaN                   NaN
1                          NaN                   NaN
2              Class Started :                   NaN
3     Attendance report till :                   NaN
4                          NaN          % Attendance
5                          NaN  BUILDING MATERIAL-II
6                          NaN                IP1102
7                      Credits                     2
8   Total no. of classes taken                    22
9             PRASENJEET RAJOO                   100
10             REETUPARNA JENA                    77
11           SURAJ KUMAR SAHOO                    88
12               LAVANYA PATRO                    94
13             ASHUTOSH DARJEE                    75
14                 UMESH MEHER                   100
15    RUDRA NARAYAN PATTANAYAK                    82
16             SIMRON PRIYANSI                    76
17                 PIYUSH NAIK                    78
18         SREEYA SAYALI SAMAL                   100
19              UPPASANA HOTTA                    78
20        CHINMAYA KUMAR MAJHI                    75
21              MOHNISH PADHEE                    35
22       BISHNU PRIYA MAHARANA                   100
23                 DINESH NAIK                    76
24     DIBYANSHU PRIYADARSINEE                    80
25    SUBHAM PRIYADARSHANI DAS                    81
26         REETUPRANGYA BEHERA                    75
27                         NaN     Srabani Upadhyaya
28                         NaN                   NaN

                     Unnamed: 4             Unnamed: 5  \
0                           NaN                    NaN
1                           NaN                    NaN
2                           NaN                    NaN
3                           NaN                    NaN
4                           NaN                    NaN
5   CLIMATOLOGY IN ARCHITECTURE  ENGINEERING MECHANICS
6                        IP1104                 IP1432
7                             3                      3
8                            26                     30
9                            92                     89
10                           96                     78
11                           81                     75
12                           81                     80
13                           76                     75
14                           96                     75
15                           81                     75
16                           92                     83
17                           92                     83
18                          100                     93
19                           76                     77
20                           76                     77
21                           42                     23
22                           92                    100
23                           81                     75
24                          100                     75
25                           84                     78
26                           76                     75
27              Sushmita Biswal       Sudhabanti Sahoo
28                          NaN                    NaN

                   Unnamed: 6                       Unnamed: 7  \
0                         NaN                              NaN
1                         NaN                              NaN
2                         NaN                              NaN
3                         NaN                              NaN
4                         NaN                              NaN
5   HISTORY OF ARCHITECTURE-I  ARCHITECTURAL DESIGN STUDIO – I
6                      IP1106                           IP1504
7                           3                                3
8                          30                               24
9                          94                              100
10                         77                               84
11                         77                               88
12                         77                              100
13                         77                               88
14                         94                               92
15                         84                               84
16                        100                               92
17                         77                               92
18                        100                              100
19                         77                               79
20                         80                               88
21                         30                               50
22                         94                              100
23                         77                               84
24                         77                               92
25                         77                               96
26                         77                               79
27    Ananya Sreyanshri Nanda          Ananya Sreyanshri Nanda
28                        NaN              and Lopamudra Nayak

                  Unnamed: 8               Unnamed: 9  \
0                        NaN                      NaN
1                        NaN                      NaN
2                        NaN                      NaN
3                        NaN                      NaN
4                        NaN                      NaN
5   BUILDING CONSTRUCTION-II  DESCRIPTIVE GEOMETRY-II
6                     IP1502                   IP1506
7                        4.5                        3
8                         25                       20
9                         96                      100
10                        76                       75
11                        80                       95
12                        88                       90
13                        76                       75
14                        80                       90
15                        76                       80
16                        76                       85
17                        84                       80
18                        90                       95
19                        80                       80
20                        76                       75
21                        52                        0
22                       100                      100
23                        76                       90
24                        84                       90
25                        76                       80
26                        58                       55
27         Srabani Upadhyaya          Sushmita Biswal
28                       NaN                      NaN

                           Unnamed: 10
0                                  NaN
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
5   DOCUMENTATION AND MEASURED DRAWING
6                               IP1508
7                                  1.5
8                                   10
9                                  100
10                                  90
11                                  90
12                                  80
13                                  90
14                                  90
15                                  80
16                                  80
17                                 100
18                                 100
19                                  90
20                                 100
21                                  30
22                                 100
23                                  80
24                                  90
25                                  80
26                                  80
27             Ananya Sreyanshri Nanda
28                                 NaN

In [7]:
attendance_df.shape

(29, 11)

In [ ]:
##due to unavailability of proper datasets i am skipping this pandas topic and will learn it during building projects